Upgrade packages and move to ESLint
rubensworks/rdf-string-ttl.js pull request #4
Opened 2022-10-04 15:26 UTC by benjay10

Remove old deprecated TSLint and move to ESLint.

As a newcomer to TypeScript, I'm not familiar with the tools. Trying to run the code from this repository led to package dependency problems, probably caused by newer version of TypeScript conflicting the maximum supported versions of TypeScript compatible with the TSLint system. With this PR I tried to move to ESLint instead with the same, mostly default configuration, update some other packages, and solve some minor linting issues at once.

2022-10-05 06:21 UTC, rubensworks commented
Thanks for this @benjay10! A migration to eslint has indeed been needed for a while.

However, to have some consistency across projects, I always use the same eslint config within my projects.
Would it be possible to copy the eslint setup as used here: https://github.com/rubensworks/rdf-data-factory.js ?

2022-10-07 04:10 UTC, benjay10 commented
I think this is now more in line with the rest of your projects.

By introducing the new ESLint configuration, there were hundreds of linting problems, of course. I hope nothing has broken. Probably not as all the tests were still correct.
There is also still some problem with package dependency version. Your `@rubensworks/eslint-config` relies on older `@typescript-eslint/eslint-plugin` (and other) packages, so I had to downgrade them here.

2022-10-07 06:10 UTC, rubensworks requested changes
Looks perfect!
Just one minor thing, then this should be good to go 🙂

2022-10-07 06:10 UTC, rubensworks commented on package.json
> +  "resolutions": {
This can be removed.

2022-10-07 16:09 UTC, benjay10 commented on package.json
> +  "resolutions": {
Done

2022-10-10 09:06 UTC, merged

2022-10-10 09:06 UTC, rubensworks commented
Thanks @benjay10!